#!/bin/bash
echo "obase=bestchol; ibase=water; $WATER" | tr 'waterstir.01234' '01234waterstir.' | awk '{n=0; for(i=1;i<=length;i++) n=n*8+index("bestchol",substr($0,i,1))-1; print substr("bestchol",n%8+1,1)}'
